name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for pointing out an issue. If we find the issue valid, we'll assign it to someone."
        pr-message: "Hey! You've just made your first contribution to the Astronomy and Physics Society's repository. If your PR passes all our checks without having merge conflicts, we'll merge your PR! If you have any issues or doubts feel free to reach out to me (owner) or any of the maintainers."
